# config/routes.yaml

# the "app_lucky_number" route name is not important yet
app_quack:
  path: /Quack
  controller: App\Controller\QuackEntityController::index

app_inscription:
  path: /inscription
  controller: App\Controller\SecurityController::registration
